FROM node:18-alpine AS development

WORKDIR /workdir-backend/src/app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:18-alpine AS production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

COPY --from=development /workdir-backend/src/app/dist ./dist
COPY --chown=node:node . /workdir-backend/src/app

USER node

CMD ["node", "dist/main"]