version: "3.9"
services:

  frontend:
    container_name: soundmachine-frontend
    build: 
      context: ../frontend
      dockerfile: Dockerfile.frontend
    ports:
        - "80:4200"

  backend:
    build: ../backend
    ports: 
      - "3000:3000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password